# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\necho.proto\x12\x04\x65\x63ho\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\"\x18\n\tEchoReply\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\x32\x36\n\x06\x45\x63hoer\x12,\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x0f.echo.EchoReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _globals['_ECHOREQUEST']._serialized_start = 20
    _globals['_ECHOREQUEST']._serialized_end = 46
    _globals['_ECHOREPLY']._serialized_start = 48
    _globals['_ECHOREPLY']._serialized_end = 72
    _globals['_ECHOER']._serialized_start = 74
    _globals['_ECHOER']._serialized_end = 128
# @@protoc_insertion_point(module_scope)
